name: Build Linux DEB
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest # Runs on a Linux virtual machine
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot # Required for jpackage to build .deb

      - name: Build with Maven
        run: mvn clean package

      - name: Create Linux Installer
        run: |
          jpackage --name "HashMaster" \
                   --type deb \
                   --module com.ykatsatos.hashMaster/com.ykatsatos.hashmaster.HashMasterApplication \
                   --module-path "target/HashMaster-1.0-SNAPSHOT.jar:target/libs" \
                   --app-version "1.0.0" \
                   --vendor "IEKatsatos" \
                   --install-dir /opt/hashmaster \
                   --linux-shortcut

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb-installer
          path: "*.deb"
